//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class calcul_sieges
    {
        public Nullable<short> sieges_elus { get; set; }
        public Nullable<short> sieges_cc { get; set; }
        public Nullable<short> sieges_secteurs { get; set; }
        public string insee { get; set; }
        public int annee { get; set; }
        public int idListe { get; set; }
    
        public virtual AnneeElection AnneeElection { get; set; }
        public virtual Liste Liste { get; set; }
        public virtual Commune Commune { get; set; }
    }
}
