//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commune
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commune()
        {
            this.calcul_sieges = new HashSet<calcul_sieges>();
            this.election = new HashSet<election>();
            this.stats_election = new HashSet<stats_election>();
        }
    
        public string insee { get; set; }
        public string code_de_la_commune { get; set; }
        public string libelle_de_la_commune { get; set; }
        public string geo_point_2d { get; set; }
        public string geo_shape { get; set; }
        public short code_du_departement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calcul_sieges> calcul_sieges { get; set; }
        public virtual Departement Departement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<election> election { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stats_election> stats_election { get; set; }
    }
}
