//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class election
    {
        public Nullable<int> voix { get; set; }
        public int annee { get; set; }
        public int idCandidat { get; set; }
        public string insee { get; set; }
    
        public virtual AnneeElection AnneeElection { get; set; }
        public virtual Candidat Candidat { get; set; }
        public virtual Commune Commune { get; set; }
    }
}
