//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testJSON
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class election_municipaleEntities : DbContext
    {
        public election_municipaleEntities()
            : base("name=election_municipaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnneeElection> AnneeElection { get; set; }
        public virtual DbSet<calcul_sieges> calcul_sieges { get; set; }
        public virtual DbSet<Candidat> Candidat { get; set; }
        public virtual DbSet<Commune> Commune { get; set; }
        public virtual DbSet<Departement> Departement { get; set; }
        public virtual DbSet<election> election { get; set; }
        public virtual DbSet<Liste> Liste { get; set; }
        public virtual DbSet<Parti> Parti { get; set; }
        public virtual DbSet<stats_election> stats_election { get; set; }
    }
}
