//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testJSON
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats_election
    {
        public Nullable<int> inscrits { get; set; }
        public Nullable<int> abstentions { get; set; }
        public Nullable<int> blancs_et_nuls { get; set; }
        public Nullable<int> exprimes { get; set; }
        public int annee { get; set; }
        public string insee { get; set; }
        public Nullable<int> votants { get; set; }
    
        public virtual AnneeElection AnneeElection { get; set; }
        public virtual Commune Commune { get; set; }
    }
}
